[project]
name = "blitz-utils"
version = "0.1.1"
authors = [ 
	{ name="Jylpah", email="jylpah@gmail.com"} 
	]
description = "Python utils for Wargaming's World of Tanks Blitz game "
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
	"Development Status :: 2 - Pre-Alpha",
	"Environment :: Console", 
	"Framework :: Pydantic",
	"Framework :: aiohttp",
	"Topic :: Games/Entertainment"
]

[project.urls]
"Homepage" = "https://github.com/Jylpah/blitz-utils"
"Bug Tracker" = "https://github.com/Jylpah/blitz-utils/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["src/blitzutils"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

[tool.pyright]
reportGeneralTypeIssues = false