[project]
name = "blitz-utils"
version = "0.1.17"
authors = [{ name = "Jylpah", email = "jylpah@gmail.com" }]
description = "Python utils for Wargaming's World of Tanks Blitz game "
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Framework :: Pydantic",
    "Framework :: aiohttp",
    "Topic :: Games/Entertainment",
]
dependencies = [
    "aiofiles>=23.1.0",
    "aiohttp>=3.8.4",
    "aiosqlite>=0.19.0",
    "isort>=5.12.0",
    "pyarrow>=11.0.0",
    "pydantic>=1.10.7",
    "pymongo>=4.3.3",
    "pyutils @ git+https://github.com/Jylpah/pyutils.git",
]

[project.optional-dependencies]
dev = [
    "build>=0.10.0",
    "mypy==1.2.0",
    "pip-chill==1.0.3",
    "pytest",
    "pytest-asyncio",
    "pytest-datafiles",
    "pytest-cov>=4",
    "pytest-timeout",
    "types-aiofiles>=23.1.0.1",
    "pyutils[dev] @ git+https://github.com/Jylpah/pyutils.git@dev",
]

[project.urls]
"Homepage" = "https://github.com/Jylpah/blitz-utils"
"Bug Tracker" = "https://github.com/Jylpah/blitz-utils/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/blitzutils"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.black]
# line-length = 100
include = '\.pyi?$'


[tool.pyright]
reportGeneralTypeIssues = false


[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-v --cov=src"
filterwarnings = [
    'ignore:Inheritance class ThrottledClientSession from ClientSession is discouraged:DeprecationWarning',
]
